version: '3'

services:
  #########################################################################
  # bitcoin client
  #########################################################################
  btc-node:
    build:
      context: ./containers/node/btc/
      dockerfile: Dockerfile
      args:
        USER_NAME: $USER
    volumes:
      - ./containers/node/btc/data:/home/${USER}/.bitcoin
    user: ${USERID}:${GID}
    ports:
      - "19332:18332"
    stdin_open: true
    tty: true
    command: /usr/bin/bitcoind --printtoconsole

  #########################################################################
  # bitcoin cash client
  #########################################################################
  bch-node:
    build:
      context: ./containers/node/bch/
      dockerfile: Dockerfile
      args:
        USER_NAME: $USER
    user: ${USERID}:${GID}
    volumes:
      - ./containers/node/bch/data:/home/${USER}/.bitcoin
    ports:
      - "19333:18332"
    stdin_open: true
    tty: true
    command: /usr/bin/bitcoind --printtoconsole

  #########################################################################
  # ethereum client
  #########################################################################
  eth-node:
    build:
      context: .
      dockerfile: ./containers/node/eth/Dockerfile
    volumes:
      - ./containers/node/eth/data:/home/parity/.local/share/io.parity.ethereum
    ports:
      - "8545:8545"
      - "18545:18545"
      - "30303/udp"
      - "30303/tcp"
      - "5001:5001"
      - "8082:8082"
      - "8180:8180"
      - "8546:8546"
      - "33303:33303"
    stdin_open: true
    tty: true
    command: --config /home/parity/toml/config.toml --warp-barrier 4950000 --jsonrpc-interface all --jsonrpc-hosts all

  #########################################################################
  # web3js
  #########################################################################
  web3:
    build:
      context: .
      dockerfile: ./containers/web3/Dockerfile
    stdin_open: true
    tty: true
    command: node
    depends_on:
      - eth-node
    links:
      - eth-node

  #########################################################################
  # GraphDB(neo4j)
  #########################################################################
  neo4j:
    image: neo4j:3.5.4
    volumes:
      - ./containers/neo4j/data:/data
      - ./containers/neo4j/logs:/logs
    ports:
      - "7474:7474"
      - "7687:7687"

  #########################################################################
  # dapps
  #########################################################################
  dapps:
    build:
      context: .
      dockerfile: ./containers/dapps/Dockerfile
    volumes:
      - ./dapps/:/dapps
    ports:
      - "9545:9545"
      - "1234:1234"
#      - "33113:33113"
#      - "34939:34939"
#      - "40149:40149"
#      - "39507:39507"
#      - "39125:39125"
#      - "46675:46675"
#      - "35927:35927"
#      - "34051:34051"
#      - "35923:35923"
#      - "40805:40805"
#      - "46405:46405"
#      - "40035:40035"
    stdin_open: true
    tty: true
    command: bash -c "touch /d.txt && tail -f /d.txt"
